/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import elsolecito_programa.CATÁLOGOS.FRM_Catalogo;
import elsolecito_programa.CLIENTES.FRM_Clientes_Alta;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jorgegarcia
 */
public class FRM_Reportes extends javax.swing.JFrame {
        Map Parametro;
        String Companyia = "";
        String Dia = "";
        String Tipo = "";
        String path = "";
        String Mes = ""; 
        String folio = "";
        JasperReport jr = null;
    /**
     * Creates new form FRM_Reportes
     */
    public FRM_Reportes() {
        initComponents();
        this.setLocationRelativeTo(null);
                LblTC.setVisible(false);
                CBXcompañia.setVisible(false);
                
                LbMes.setVisible(false);
                TxtMes.setVisible(false);
                
                LbDia.setVisible(false);
                TxtDia.setVisible(false);
                
                LbFolio.setVisible(false);
                TxFolio.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CBXTipo = new javax.swing.JComboBox<>();
        LblTC = new javax.swing.JLabel();
        CBXcompañia = new javax.swing.JComboBox();
        BtnGenerar = new javax.swing.JButton();
        LbMes = new javax.swing.JLabel();
        TxFolio = new javax.swing.JTextField();
        LbFolio = new javax.swing.JLabel();
        TxtMes = new javax.swing.JTextField();
        LbDia = new javax.swing.JLabel();
        TxtDia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GENERADOR DE REPORTES. ");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EL SOLECITO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(179, 179, 179))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Seleccione el tipo de reporte:");

        CBXTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Existencia", "Recargas", "Detalles de Compra", "Detalles de Venta", "Ventas por Mes", "Ventas por Dia", " ", " " }));
        CBXTipo.setToolTipText("Seleccione una opción.");
        CBXTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBXTipoActionPerformed(evt);
            }
        });

        LblTC.setText("Compañía:");

        CBXcompañia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CBXcompañia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Telcel", "Unefon", "Movistar", "otro..." }));
        CBXcompañia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBXcompañiaActionPerformed(evt);
            }
        });

        BtnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        BtnGenerar.setText("Generar reporte");
        BtnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerarActionPerformed(evt);
            }
        });

        LbMes.setText("Mes:");

        TxFolio.setToolTipText("Ingrese el folio del producto.");
        TxFolio.setName("TxtFolio"); // NOI18N
        TxFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxFolioKeyTyped(evt);
            }
        });

        LbFolio.setText("Folio:");
        LbFolio.setName("LbFolio"); // NOI18N

        TxtMes.setToolTipText("Ingrese los mese del 01 al 12");
        TxtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMesKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtMesKeyReleased(evt);
            }
        });

        LbDia.setText("Día:");

        TxtDia.setToolTipText("Ingrese un día del 01 - 31");
        TxtDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDiaActionPerformed(evt);
            }
        });
        TxtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDiaKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back57.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(CBXTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(132, 132, 132)
                            .addComponent(BtnGenerar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LblTC)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LbDia)
                                    .addGap(25, 25, 25)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CBXcompañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(81, 81, 81)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LbMes)
                                .addComponent(LbFolio))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBXTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbMes)
                    .addComponent(TxtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbFolio)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBXcompañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblTC)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGenerar)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBXTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBXTipoActionPerformed
        // TODO add your handling code here:
        Tipo = "";
        Tipo = CBXTipo.getItemAt(this.CBXTipo.getSelectedIndex()).toString();
        switch(Tipo){
            case "Existencia":
                LblTC.setVisible(false);
                CBXcompañia.setVisible(false);
                
                LbMes.setVisible(false);
                TxtMes.setVisible(false);
                
                LbDia.setVisible(false);
                TxtDia.setVisible(false);
                
                LbFolio.setVisible(false);
                TxFolio.setVisible(false);
                break;

            case "Recargas":
                LblTC.setVisible(true);
                CBXcompañia.setVisible(true);
                
                LbMes.setVisible(false);
                TxtMes.setVisible(false);
                
                LbDia.setVisible(false);
                TxtDia.setVisible(false);
                
                LbFolio.setVisible(false);
                TxFolio.setVisible(false);
                break;
                    
            case "Ventas por Mes":
                LbMes.setVisible(true);
                TxtMes.setVisible(true);
                
                LbDia.setVisible(false);
                TxtDia.setVisible(false);
                
                LblTC.setVisible(false);
                CBXcompañia.setVisible(false);
                
                LbFolio.setVisible(false);
                TxFolio.setVisible(false);
                break;

            case "Ventas por Dia":
                LbMes.setVisible(false);
                TxtMes.setVisible(false);
                
                LbDia.setVisible(true);
                TxtDia.setVisible(true);
                
                LblTC.setVisible(false);
                CBXcompañia.setVisible(false);
                
                LbFolio.setVisible(false);
                TxFolio.setVisible(false);
                
            break;
            
            case "Detalles de Venta":
                LbMes.setVisible(false);
                TxtMes.setVisible(false);
                
                LbDia.setVisible(false);
                TxtDia.setVisible(false);
                
                LblTC.setVisible(false);
                CBXcompañia.setVisible(false);
                
                LbFolio.setVisible(true);
                TxFolio.setVisible(true);
            break;
            
            case "Detalles de Compra":
                LbMes.setVisible(false);
                TxtMes.setVisible(false);
                
                LbDia.setVisible(false);
                TxtDia.setVisible(false);
                
                LblTC.setVisible(false);
                CBXcompañia.setVisible(false);
                
                LbFolio.setVisible(true);
                TxFolio.setVisible(true);
                
                
            break;
            
        }
    }//GEN-LAST:event_CBXTipoActionPerformed

    private void BtnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerarActionPerformed
        // TODO add your handling code here:   
        BaseDeDatosVentas mBD = new BaseDeDatosVentas();
        
        switch(Tipo){
            case "Existencia":
                path = "";
                 path = "/Users/jorgegarcia/NetBeansProjects/ElSolecito/src/Reportes/Existencias.jasper";
               //path = "C:\\Users\\MARIA NOELDA MARIANO\\Documents\\Git\\ElSolecito_Programa\\src\\Reportes\\Existencias.jasper";
                jr = null;
                try {
                    //jr = (JasperReport)JRLoader.loadObjectFromLocation(path);
                    jr = (JasperReport) JRLoader.loadObjectFromFile(path);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, mBD.conectare());
                    JasperViewer jv = new JasperViewer(jp, false);
                    jv.setVisible(true);
                    jv.setTitle(path);
                    this.dispose();
                } catch (JRException ex) {
                    Logger.getLogger(FRM_Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;

            case "Recargas":
            Companyia = CBXcompañia.getItemAt(this.CBXcompañia.getSelectedIndex()).toString();
            Parametro = new HashMap();
            path = "";
            path = "/Users/jorgegarcia/NetBeansProjects/ElSolecito/src/Reportes/Reporte_Recargas.jasper";
            //path = "C:\\Users\\MARIA NOELDA MARIANO\\Documents\\Git\\ElSolecito_Programa\\src\\Reportes\\Reporte_Recargas.jasper";
            jr = null;
            try {
                Parametro.put("Buscar", Companyia);
                //jr = (JasperReport)JRLoader.loadObjectFromLocation(path);
                  jr = (JasperReport) JRLoader.loadObjectFromFile(path);
                JasperPrint jp = JasperFillManager.fillReport(jr, Parametro, mBD.conectare());
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);
                jv.setTitle(path);
                this.dispose();
            } catch (JRException ex) {
                Logger.getLogger(FRM_Reportes.class.getName()).log(Level.SEVERE, null, ex);
            }                
                
                break;
                    
            case "Ventas por Mes": 
            Mes = TxtMes.getText();        
            Parametro = new HashMap();
            path = "";
            path = "/Users/jorgegarcia/NetBeansProjects/ElSolecito/src/Reportes/Reporte_Venta_Mes.jasper";
            //path = "C:\\Users\\MARIA NOELDA MARIANO\\Documents\\Git\\ElSolecito_Programa\\src\\Reportes\\Reporte_Venta_Mes.jasper";
            
            jr = null;
            try {
                Parametro.put("Seleccion", Mes);
                //jr = (JasperReport)JRLoader.loadObjectFromLocation(path);
                jr = (JasperReport) JRLoader.loadObjectFromFile(path);
                JasperPrint jp = JasperFillManager.fillReport(jr, Parametro, mBD.conectare());
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);
                jv.setTitle(path);
                this.dispose();
            } catch (JRException ex) {
                Logger.getLogger(FRM_Reportes.class.getName()).log(Level.SEVERE, null, ex);
            }                
            break;
            
            case "Detalles de Compra":
            folio = TxFolio.getText();
            Parametro = new HashMap();
            path = "";
            path = "/Users/jorgegarcia/NetBeansProjects/ElSolecito/src/Reportes/Reporte_Detalle_Compra.jasper";
            //path = "C:\\Users\\MARIA NOELDA MARIANO\\Documents\\Git\\ElSolecito_Programa\\src\\Reportes\\Reporte_Detalle_Compra.jasper";
            jr = null;
            try {
                Parametro.put("Seleccion", folio);
                //jr = (JasperReport)JRLoader.loadObjectFromLocation(path);
                jr = (JasperReport) JRLoader.loadObjectFromFile(path);
                JasperPrint jp = JasperFillManager.fillReport(jr, Parametro, mBD.conectare());
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);
                jv.setTitle(path);
                this.dispose();
            } catch (JRException ex) {
                Logger.getLogger(FRM_Reportes.class.getName()).log(Level.SEVERE, null, ex);
            }                
            break;
            case "Detalles de Venta":
            folio = TxFolio.getText();
            Parametro = new HashMap();
            path = "";
            path = "/Users/jorgegarcia/NetBeansProjects/ElSolecito/src/Reportes/Reporte_Detalle_Venta.jasper";
            //path = "C:\\Users\\MARIA NOELDA MARIANO\\Documents\\Git\\ElSolecito_Programa\\src\\Reportes\\Reporte_Detalle_Venta.jasper";
            jr = null;
            try {
                Parametro.put("Buscar", folio);
                //jr = (JasperReport)JRLoader.loadObjectFromLocation(path);
                jr = (JasperReport) JRLoader.loadObjectFromFile(path);
                JasperPrint jp = JasperFillManager.fillReport(jr, Parametro, mBD.conectare());
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);
                jv.setTitle(path);
                this.dispose();
            } catch (JRException ex) {
                Logger.getLogger(FRM_Reportes.class.getName()).log(Level.SEVERE, null, ex);
            }                
            break;
            
            

            case "Ventas por Dia":
            Dia = TxtDia.getText();        
            Parametro = new HashMap();
            path = "/Users/jorgegarcia/NetBeansProjects/ElSolecito/src/Reportes/Reporte_Ventas_Dia.jasper";
            //path = "C:\\Users\\MARIA NOELDA MARIANO\\Documents\\Git\\ElSolecito_Programa\\src\\Reportes\\Reporte_Ventas_Dia.jasper";
            jr = null;
            try {
                Parametro.put("Buscar", Dia);
                jr = (JasperReport) JRLoader.loadObjectFromFile(path);
                JasperPrint jp = JasperFillManager.fillReport(jr, Parametro, mBD.conectare());
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);
                jv.setTitle(path);
                this.dispose();
            } catch (JRException ex) {
                Logger.getLogger(FRM_Reportes.class.getName()).log(Level.SEVERE, null, ex);
            }     
            break;
        }
    }//GEN-LAST:event_BtnGenerarActionPerformed

    private void CBXcompañiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBXcompañiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBXcompañiaActionPerformed

    private void TxtDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDiaActionPerformed

    private void TxtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDiaKeyTyped
        // TODO add your handling code here:
        char error = evt.getKeyChar();
        if (error < '0' || error > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_TxtDiaKeyTyped

    private void TxtMesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMesKeyReleased

    private void TxtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMesKeyTyped
        // TODO add your handling code here:
        char error = evt.getKeyChar();
        if (error < '0' || error > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_TxtMesKeyTyped

    private void TxFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxFolioKeyTyped
        // TODO add your handling code here:
        char error = evt.getKeyChar();
        if (error < '0' || error > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_TxFolioKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new FRM_Catalogo().show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Reportes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGenerar;
    private javax.swing.JComboBox<String> CBXTipo;
    private javax.swing.JComboBox CBXcompañia;
    private javax.swing.JLabel LbDia;
    private javax.swing.JLabel LbFolio;
    private javax.swing.JLabel LbMes;
    private javax.swing.JLabel LblTC;
    private javax.swing.JTextField TxFolio;
    private javax.swing.JTextField TxtDia;
    private javax.swing.JTextField TxtMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
