/*  1. Distribucion de inventario en el local El Solecito.
    2. Omar Almaraz Cordova.
    3. Creacion 17/04/18.
    4. correcion del formulario catalogo Proveedores.
*/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elsolecito_programa.PROVEEDORES;

/**
 *
 * @author 8
 */
public class FRM_Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Proveedores
     */
    public FRM_Proveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTN_Alta = new javax.swing.JButton();
        BTN_Baja = new javax.swing.JButton();
        BTN_Cambios = new javax.swing.JButton();
        BTN_Consulta = new javax.swing.JButton();
        BTN_Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel1.setText("Catalogo Proveedores");

        BTN_Alta.setText("Alta");
        BTN_Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AltaActionPerformed(evt);
            }
        });

        BTN_Baja.setText("Baja");
        BTN_Baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BajaActionPerformed(evt);
            }
        });

        BTN_Cambios.setText("Cambios");
        BTN_Cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CambiosActionPerformed(evt);
            }
        });

        BTN_Consulta.setText("Consulta");
        BTN_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ConsultaActionPerformed(evt);
            }
        });

        BTN_Menu.setText("Volver Al Menu");
        BTN_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BTN_Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(BTN_Baja, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(BTN_Cambios, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(BTN_Consulta))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(BTN_Menu)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Alta)
                    .addComponent(BTN_Baja)
                    .addComponent(BTN_Cambios)
                    .addComponent(BTN_Consulta))
                .addGap(27, 27, 27)
                .addComponent(BTN_Menu)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_BajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BajaActionPerformed
        
        FRM_Proveedores_Baja mBaja = new FRM_Proveedores_Baja();
        mBaja.show();
    }//GEN-LAST:event_BTN_BajaActionPerformed

    private void BTN_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ConsultaActionPerformed
        FRM_Proveedores_Consultas mConsultas = new FRM_Proveedores_Consultas();
        mConsultas.show();
    }//GEN-LAST:event_BTN_ConsultaActionPerformed

    private void BTN_AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AltaActionPerformed
        FRM_Proveedores_Alta mAlta = new FRM_Proveedores_Alta();
        mAlta.show();
    }//GEN-LAST:event_BTN_AltaActionPerformed

    private void BTN_CambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CambiosActionPerformed
        FRM_Proveedores_Cambios mCambios = new FRM_Proveedores_Cambios();
        mCambios.show();
    }//GEN-LAST:event_BTN_CambiosActionPerformed

    private void BTN_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MenuActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTN_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Alta;
    private javax.swing.JButton BTN_Baja;
    private javax.swing.JButton BTN_Cambios;
    private javax.swing.JButton BTN_Consulta;
    private javax.swing.JButton BTN_Menu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
