/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package COMPRAS;

import elsolecito_programa.CLIENTES.ClientesDeudores;
import elsolecito_programa.PROVEEDORES.Proveedores;
import elsolecito_programa.Producto.Producto;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jorgegarcia
 */
public class FRM_Compras extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Compras
     */
    public FRM_Compras() {
        initComponents();
        this.setLocationRelativeTo(null);
        setFilas_Proveedores();
        setCompras();
        setCompra();
        Tabla_Compras.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (Tabla_Compras.getSelectedRow() != -1) {
                    int fila = Tabla_Compras.getSelectedRow();
                    TXT_Nombre.setText(Tabla_Compras.getValueAt(fila, 0).toString());
                }
            }
        });

    }
    //INSTANCIA DE TODOS LAS CLASES A USAR...
    BaseDeDatos mBD = new BaseDeDatos();
    Compras mCompras = new Compras();
    DetalleCompra mDCompra = new DetalleCompra();
    Proveedores mProveedor = new Proveedores();
    Producto mProducto = new Producto();
    DefaultTableModel modeloTabla = new DefaultTableModel();
    int ContColumn = 1;
    int RegistroCompra = 0;
    float TotalCompleto = 0;
    float TotalTemporal = 0;
    float ResultadoCompraTotal = 0;
    float Nueva_Cantidad = 0;
    int ContadorColumna = 1;
    int ContadorColumnaProveedor = 1;
    DefaultTableModel TablaProveedores = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Compras = new javax.swing.JTable();
        TXT_Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla_Proveedores = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LBL_Precio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LBL_Desc = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LBL_Proveedor = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        TXT_N_Cantidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        LBL_TotalP = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LBL_Nombre_Producto = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("COMPRAS DE PRODUCTOS.");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EL SOLECITO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(343, 343, 343))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Tabla_Compras.setModel(modeloTabla);
        Tabla_Compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_ComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Compras);

        jLabel1.setText("Código:");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("REGISTRO DE PRODUCTOS EN EL SISTEMA.");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setText("REGISTRO DE PROVEEDORES EN EL SISTEMA.");

        Tabla_Proveedores.setModel(TablaProveedores);
        jScrollPane4.setViewportView(Tabla_Proveedores);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setText("INGRESE LOS DATOS:");

        jLabel2.setText("Precio:");

        jLabel11.setText("Descripción:");

        jLabel13.setText("Proveedor:");

        jLabel15.setText("Cantidad:");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel16.setText("Total a pagar:");

        jLabel18.setText("Nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBL_TotalP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel18))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_Nombre_Producto)
                            .addComponent(TXT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_N_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_Proveedor)
                            .addComponent(LBL_Precio)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(LBL_Desc))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TXT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_Nombre_Producto)
                            .addComponent(jLabel18))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(LBL_Desc))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LBL_Precio))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_Proveedor)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TXT_N_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_TotalP)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/screen6.png"))); // NOI18N
        jButton1.setText("Mostrar datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jButton2.setText("Seleccionar producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        jButton5.setText("Guardar compra");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registry24.png"))); // NOI18N
        jButton3.setText("Finalizar compra");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back57.png"))); // NOI18N
        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(35, 35, 35)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    void borrar() {
        DefaultTableModel LimpiadoTabla = (DefaultTableModel) Tabla_Compras.getModel();
        //Borramosla tabla...
        int a = Tabla_Compras.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {
            LimpiadoTabla.removeRow(LimpiadoTabla.getRowCount() - 1);
        }
    }

    void borrar_proveedores() {
        DefaultTableModel LimpiadoTabla = (DefaultTableModel) Tabla_Proveedores.getModel();
        //Borramosla tabla...
        int a = Tabla_Proveedores.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {
            LimpiadoTabla.removeRow(LimpiadoTabla.getRowCount() - 1);
        }
    }

    void setCompras() {
        borrar();

        if (mBD.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mBD.ConsultarProductos();
            String[] Datos = null;
            if (mArrayList != null) {
                if (ContColumn == 1) {
                    //modeloTabla.addColumn("id_producto");
                    modeloTabla.addColumn("Folio");
                    modeloTabla.addColumn("Nombre");
                    modeloTabla.addColumn("Precio");
                    //modeloTabla.addColumn("Cantidad");
                    modeloTabla.addColumn("Descripción");

                    ContColumn = 2;
                }
                for (int i = 0; i < mArrayList.size(); i++) {
                    mProducto = (Producto) mArrayList.get(i);
                    Datos = new String[4];
                    Datos[0] = "" + mProducto.getCodigo();
                    Datos[1] = mProducto.getNombre();
                    Datos[2] = "" + mProducto.getPrecio();
                    //Datos[3] = "" + mProducto.getCantidadProducto();
                    Datos[3] = mProducto.getDesc_Prod();

                    modeloTabla.addRow(Datos);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No existe ese Producto...");
        }
        this.Tabla_Compras = new javax.swing.JTable();
        this.Tabla_Compras.setModel(modeloTabla);
        this.Tabla_Compras.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.Tabla_Compras.getColumnModel().getColumn(1).setPreferredWidth(100);
        this.Tabla_Compras.getColumnModel().getColumn(2).setPreferredWidth(400);
        this.Tabla_Compras.getColumnModel().getColumn(3).setPreferredWidth(600);
        //this.Tabla_Compras.getColumnModel().getColumn(4).setPreferredWidth(400);

        if (this.Tabla_Compras.getRowCount() > 0) {
            this.Tabla_Compras.setRowSelectionInterval(0, 0);
        } else {
            JOptionPane.showMessageDialog(null, "Error al consultar");
        }
        mBD.desconectar();
    }

    void setFilas_Proveedores() {
        borrar_proveedores();

        if (mBD.conectar()) {
            ArrayList mArrayListProveedores = new ArrayList();
            mArrayListProveedores = mBD.ConsultaTodoProveedor();
            String[] Datos = null;
            if (mArrayListProveedores != null) {
                if (ContadorColumnaProveedor == 1) {
                    TablaProveedores.addColumn("Folio");
                    TablaProveedores.addColumn("Nombre");
                    TablaProveedores.addColumn("Marca");
                    ContadorColumnaProveedor = 2;
                }
                for (int i = 0; i < mArrayListProveedores.size(); i++) {
                    mProveedor = (Proveedores) mArrayListProveedores.get(i);
                    Datos = new String[3];
                    Datos[0] = mProveedor.getFolio();
                    Datos[1] = mProveedor.getNombre();
                    Datos[2] = mProveedor.getMarca();
                    TablaProveedores.addRow(Datos);
                }

            } else {
                JOptionPane.showMessageDialog(null, "No existe el proveedor...");
            }
            this.Tabla_Proveedores = new javax.swing.JTable();
            this.Tabla_Proveedores.setModel(TablaProveedores);
            this.Tabla_Proveedores.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.Tabla_Proveedores.getColumnModel().getColumn(1).setPreferredWidth(100);
            this.Tabla_Proveedores.getColumnModel().getColumn(2).setPreferredWidth(200);
            if (this.Tabla_Proveedores.getRowCount() > 0) {
                this.Tabla_Proveedores.setRowSelectionInterval(0, 0);
            }
        }
    }

    void setCompra() {
        Calendar fecha = new GregorianCalendar();
        String FechaActual = "" + fecha.get(Calendar.YEAR) + "-" + fecha.get(Calendar.MONTH) + "-" + fecha.get(Calendar.DAY_OF_MONTH);
        System.out.println();

        mCompras.setFecha(FechaActual);
        mCompras.setTotalCompras(ResultadoCompraTotal);
        mCompras.setFolio(this.TXT_Nombre.getText());
        
        if (mBD.conectar()) {
            if (mBD.AltaCompra(mCompras)) {
                RegistroCompra = (mBD.ConsultaFolioCompra());
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar Compra");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error al consultar");
        }
        mBD.desconectar();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Se programa el botón para mostrar los datos en la tabla de compras.
        borrar();

        if (mBD.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mBD.ConsultarProductos();
            String[] Datos = null;
            if (mArrayList != null) {
                if (ContColumn == 1) {
                    //modeloTabla.addColumn("id_producto");
                    modeloTabla.addColumn("Folio");
                    modeloTabla.addColumn("Nombre");
                    modeloTabla.addColumn("Precio");
                    //modeloTabla.addColumn("Cantidad");
                    modeloTabla.addColumn("Descripción");

                    ContColumn = 2;
                }
                for (int i = 0; i < mArrayList.size(); i++) {
                    mProducto = (Producto) mArrayList.get(i);
                    Datos = new String[4];
                    Datos[0] = "" + mProducto.getCodigo();
                    Datos[1] = mProducto.getNombre();
                    Datos[2] = "" + mProducto.getPrecio();
                    //Datos[3] = "" + mProducto.getCantidadProducto();
                    Datos[3] = mProducto.getDesc_Prod();

                    modeloTabla.addRow(Datos);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No existe ese Producto...");
        }
        this.Tabla_Compras = new javax.swing.JTable();
        this.Tabla_Compras.setModel(modeloTabla);
        this.Tabla_Compras.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.Tabla_Compras.getColumnModel().getColumn(1).setPreferredWidth(100);
        this.Tabla_Compras.getColumnModel().getColumn(2).setPreferredWidth(400);
        this.Tabla_Compras.getColumnModel().getColumn(3).setPreferredWidth(600);
        //this.Tabla_Compras.getColumnModel().getColumn(4).setPreferredWidth(400);

        if (this.Tabla_Compras.getRowCount() > 0) {
            this.Tabla_Compras.setRowSelectionInterval(0, 0);
        } else {
            JOptionPane.showMessageDialog(null, "Error al consultar");
        }
        mBD.desconectar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        borrar();
        if (mBD.conectar()) {
            Producto mProducto = mBD.ConsultarEspecifica(TXT_Nombre.getText());
            String[] Datos;

            if (mProducto != null) {
                if (ContColumn == 1) {
                    modeloTabla.addColumn("Folio");
                    modeloTabla.addColumn("Nombre");
                    modeloTabla.addColumn("Precio");
                    //modeloTabla.addColumn("Cantidad");
                    modeloTabla.addColumn("Descripción");
                    //modeloTabla.addColumn("id_proveedor");
                    ContColumn = 2;
                }
                Datos = new String[4];

                Datos[0] = "" + mProducto.getCodigo();
                Datos[1] = mProducto.getNombre();
                Datos[2] = "" + mProducto.getPrecio();
                Datos[3] = mProducto.getDesc_Prod();
                //Datos[4] = mProducto.getDesc_Prod();

                LBL_Nombre_Producto.setText(mProducto.getNombre());
                LBL_Proveedor.setText("" + mProducto.getId_proveedor());
                LBL_Precio.setText("" + mProducto.getPrecio());
                LBL_Desc.setText(mProducto.getDesc_Prod());

                modeloTabla.addRow(Datos);
            } else {
                JOptionPane.showMessageDialog(null, "No existe ese Producto...");
            }
            this.Tabla_Compras = new javax.swing.JTable();
            this.Tabla_Compras.setModel(modeloTabla);
            this.Tabla_Compras.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.Tabla_Compras.getColumnModel().getColumn(1).setPreferredWidth(100);
            this.Tabla_Compras.getColumnModel().getColumn(2).setPreferredWidth(400);
            this.Tabla_Compras.getColumnModel().getColumn(3).setPreferredWidth(600);
            //this.Tabla_Compras.getColumnModel().getColumn(4).setPreferredWidth(400);

            if (this.Tabla_Compras.getRowCount() > 0) {
                this.Tabla_Compras.setRowSelectionInterval(0, 0);
            } else {
                JOptionPane.showMessageDialog(null, "Error al consultar");
            }
            mBD.desconectar();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Tabla_ComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_ComprasMouseClicked
        // TODO add your handling code here:
        //borrar();
        if (mBD.conectar()) {
            Producto mProducto = mBD.ConsultarEspecifica(TXT_Nombre.getText());
            String[] Datos;

            if (mProducto != null) {
                if (ContColumn == 1) {
                    modeloTabla.addColumn("Folio");
                    modeloTabla.addColumn("Nombre");
                    modeloTabla.addColumn("Precio");
                    //modeloTabla.addColumn("Cantidad");
                    modeloTabla.addColumn("Descripción");
                    //modeloTabla.addColumn("id_proveedor");
                    ContColumn = 2;
                }
                Datos = new String[4];

                Datos[0] = "" + mProducto.getCodigo();
                Datos[1] = mProducto.getNombre();
                Datos[2] = "" + mProducto.getPrecio();
                Datos[3] = mProducto.getDesc_Prod();
                //Datos[4] = mProducto.getDesc_Prod();

                LBL_Nombre_Producto.setText(mProducto.getNombre());
                LBL_Proveedor.setText("" + mBD.ConsultaProveedor(mProducto.getCodigo()));
                LBL_Precio.setText("" + mProducto.getPrecio());
                LBL_Desc.setText(mProducto.getDesc_Prod());

                modeloTabla.addRow(Datos);
            } else {
                JOptionPane.showMessageDialog(null, "No existe ese Producto...");
            }
            this.Tabla_Compras = new javax.swing.JTable();
            this.Tabla_Compras.setModel(modeloTabla);
            this.Tabla_Compras.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.Tabla_Compras.getColumnModel().getColumn(1).setPreferredWidth(100);
            this.Tabla_Compras.getColumnModel().getColumn(2).setPreferredWidth(400);
            this.Tabla_Compras.getColumnModel().getColumn(3).setPreferredWidth(600);
            //this.Tabla_Compras.getColumnModel().getColumn(4).setPreferredWidth(400);

            if (this.Tabla_Compras.getRowCount() > 0) {
                this.Tabla_Compras.setRowSelectionInterval(0, 0);
            } else {
                JOptionPane.showMessageDialog(null, "Error al consultar");
            }
            mBD.desconectar();
        }
    }//GEN-LAST:event_Tabla_ComprasMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //Le damos valores a los ID.
        Producto nProducto = new Producto();
        mProducto.setId_producto(Integer.parseInt(TXT_Nombre.getText()));
        mProveedor.setId_proveedor(Integer.parseInt(mProveedor.getFolio()));

        mBD.conectar();
        Producto mProductoOld = mBD.consultarProducto(Integer.parseInt(this.TXT_Nombre.getText()));
        mBD.desconectar();

        //Nueva_Cantidad = Float.parseFloat(TXT_N_Cantidad.getText()) + mProductoOld.getCantidadProducto();
        nProducto.setNombre(LBL_Nombre_Producto.getText());
        nProducto.setPrecio(Float.parseFloat(LBL_Precio.getText()));
        nProducto.setCantidadProducto(Integer.parseInt(TXT_N_Cantidad.getText()));
        nProducto.setDesc_Prod(LBL_Desc.getText());
        Nueva_Cantidad = 0;

        if (mBD.conectar()) {
            if (mBD.ModificarProductos(nProducto, nProducto)) {
                JOptionPane.showMessageDialog(null, "Productos agregados con éxito.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al añadir.");
            }

            Compras mCompraConsulta = mBD.ConsultaTodaCompra(this.TXT_Nombre.getText());
            //Solo para verificar...

            mDCompra.setCantidad(Integer.parseInt(TXT_N_Cantidad.getText()));
            mDCompra.setPrecio(Float.parseFloat(LBL_Precio.getText()));

            mDCompra.setId_producto(Integer.parseInt(mProducto.getCodigo()));
            mDCompra.setId_proveedor(Integer.parseInt(mProveedor.getFolio()));
            
            mDCompra.setId_detalle(RegistroCompra);

            TotalTemporal = Float.parseFloat(LBL_Precio.getText()) * Float.parseFloat(TXT_N_Cantidad.getText());
            TotalCompleto = TotalTemporal + TotalCompleto;
            LBL_TotalP.setText(String.valueOf(TotalCompleto));

            if (mBD.AltaDetalleCompra(mDCompra)) {
                JOptionPane.showMessageDialog(null, "Detalle guardado.");
            } else {
                JOptionPane.showMessageDialog(null, "No se guardo el detalle guardado.");
            }
        }
        //TXT_N_Cantidad.setText("");
        //TXT_Nombre.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Compras mCompraAlterada = new Compras();
            mCompras.setFolio("" +RegistroCompra);
            mCompraAlterada.setTotalCompras(Float.parseFloat(LBL_TotalP.getText()));
            if(mBD.conectar()) 
            {
                if (mBD.CambiosCompra(mCompras, mCompraAlterada))
                {
                    JOptionPane.showMessageDialog(null,"NUEVO PRECIO EN LA COMPRA");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"ERROR EN NUEVO PRECIO");
                }
            }
            mBD.desconectar();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Compras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_Desc;
    private javax.swing.JLabel LBL_Nombre_Producto;
    private javax.swing.JLabel LBL_Precio;
    private javax.swing.JLabel LBL_Proveedor;
    private javax.swing.JLabel LBL_TotalP;
    private javax.swing.JTextField TXT_N_Cantidad;
    private javax.swing.JTextField TXT_Nombre;
    private javax.swing.JTable Tabla_Compras;
    private javax.swing.JTable Tabla_Proveedores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
